// Mocks generated by Mockito 5.4.5 from annotations
// in flower_e_commerce_app/test/Feature/mainLayout/tabs/categoriesFeature/presentation/viewModel/viewModel/categories_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_e_commerce_app/core/Errors/api_results.dart' as _i4;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/categoriesFeature/domain/entities/responseEntities/categories_response_entity.dart'
    as _i5;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/categoriesFeature/domain/entities/responseEntities/product_response_entity.dart'
    as _i8;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/categoriesFeature/domain/useCases/categories_use_case.dart'
    as _i2;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/categoriesFeature/domain/useCases/get_all_products_use_case.dart'
    as _i9;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/categoriesFeature/domain/useCases/get_category_products_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesUseCase extends _i1.Mock implements _i2.CategoriesUseCase {
  MockCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.CategoryResponseEntity>> invoke() =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.CategoryResponseEntity>>.value(
                _i6.dummyValue<_i4.ApiResult<_i5.CategoryResponseEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CategoryResponseEntity>>);
}

/// A class which mocks [GetCategoryProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoryProductsUseCase extends _i1.Mock
    implements _i7.GetCategoryProductsUseCase {
  MockGetCategoryProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i8.ProductResponseEntity>> invoke({
    required String? categoryId,
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
          {
            #categoryId: categoryId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i8.ProductResponseEntity>>.value(
            _i6.dummyValue<_i4.ApiResult<_i8.ProductResponseEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
            {
              #categoryId: categoryId,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.ProductResponseEntity>>);
}

/// A class which mocks [GetAllProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProductsUseCase extends _i1.Mock
    implements _i9.GetAllProductsUseCase {
  MockGetAllProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i8.ProductResponseEntity>> invoke() =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i8.ProductResponseEntity>>.value(
            _i6.dummyValue<_i4.ApiResult<_i8.ProductResponseEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.ProductResponseEntity>>);
}
