// Mocks generated by Mockito 5.4.6 from annotations
// in flower_e_commerce_app/test/Feature/mainLayout/tabs/profile/api/dataSources/profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;

import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/profile/api/client/profile_api_service.dart'
    as _i5;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/profile/api/models/request/edit_profile_request_model.dart'
    as _i7;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/profile/api/models/response/edit_profile_response_dto.dart'
    as _i3;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/profile/api/models/response/logged_user_data_response_dto.dart'
    as _i2;
import 'package:flower_e_commerce_app/Feature/mainLayout/tabs/profile/api/models/response/upload_photo_response_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoggedUserDataResponseDto_0 extends _i1.SmartFake
    implements _i2.LoggedUserDataResponseDto {
  _FakeLoggedUserDataResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseDto_1 extends _i1.SmartFake
    implements _i3.EditProfileResponseDto {
  _FakeEditProfileResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPhotoResponseDto_2 extends _i1.SmartFake
    implements _i4.UploadPhotoResponseDto {
  _FakeUploadPhotoResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiService extends _i1.Mock implements _i5.ProfileApiService {
  MockProfileApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.LoggedUserDataResponseDto> getLoggedUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLoggedUserData,
          [],
        ),
        returnValue: _i6.Future<_i2.LoggedUserDataResponseDto>.value(
            _FakeLoggedUserDataResponseDto_0(
          this,
          Invocation.method(
            #getLoggedUserData,
            [],
          ),
        )),
      ) as _i6.Future<_i2.LoggedUserDataResponseDto>);

  @override
  _i6.Future<_i3.EditProfileResponseDto> editProfile(
          _i7.EditProfileRequestModel? editProfileRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [editProfileRequest],
        ),
        returnValue: _i6.Future<_i3.EditProfileResponseDto>.value(
            _FakeEditProfileResponseDto_1(
          this,
          Invocation.method(
            #editProfile,
            [editProfileRequest],
          ),
        )),
      ) as _i6.Future<_i3.EditProfileResponseDto>);

  @override
  _i6.Future<_i4.UploadPhotoResponseDto> uploadProfilePhoto(_i8.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePhoto,
          [photo],
        ),
        returnValue: _i6.Future<_i4.UploadPhotoResponseDto>.value(
            _FakeUploadPhotoResponseDto_2(
          this,
          Invocation.method(
            #uploadProfilePhoto,
            [photo],
          ),
        )),
      ) as _i6.Future<_i4.UploadPhotoResponseDto>);
}
