// Mocks generated by Mockito 5.4.6 from annotations
// in flower_e_commerce_app/test/Feature/occasion/api/dataSources/occasion_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_e_commerce_app/Feature/occasion/api/client/occasion_api_service.dart'
    as _i4;
import 'package:flower_e_commerce_app/Feature/occasion/api/models/response/occasion_response_dto.dart'
    as _i2;
import 'package:flower_e_commerce_app/Feature/occasion/api/models/response/product_by_occasion_response_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOccasionResponseDto_0 extends _i1.SmartFake
    implements _i2.OccasionResponseDto {
  _FakeOccasionResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductByOccasionResponseDto_1 extends _i1.SmartFake
    implements _i3.ProductByOccasionResponseDto {
  _FakeProductByOccasionResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OccasionApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOccasionApiService extends _i1.Mock
    implements _i4.OccasionApiService {
  MockOccasionApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.OccasionResponseDto> getAllOccasions() => (super.noSuchMethod(
        Invocation.method(
          #getAllOccasions,
          [],
        ),
        returnValue: _i5.Future<_i2.OccasionResponseDto>.value(
            _FakeOccasionResponseDto_0(
          this,
          Invocation.method(
            #getAllOccasions,
            [],
          ),
        )),
      ) as _i5.Future<_i2.OccasionResponseDto>);

  @override
  _i5.Future<_i3.ProductByOccasionResponseDto> getProductsByOccasion(
          String? occasionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByOccasion,
          [occasionId],
        ),
        returnValue: _i5.Future<_i3.ProductByOccasionResponseDto>.value(
            _FakeProductByOccasionResponseDto_1(
          this,
          Invocation.method(
            #getProductsByOccasion,
            [occasionId],
          ),
        )),
      ) as _i5.Future<_i3.ProductByOccasionResponseDto>);
}
