// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxKCX21RQesh5kknlNIv8WLqmmgZj6MEM',
    appId: '1:499992457670:web:66b750198d699a221482c7',
    messagingSenderId: '499992457670',
    projectId: 'flowery-cf7c0',
    authDomain: 'flowery-cf7c0.firebaseapp.com',
    storageBucket: 'flowery-cf7c0.firebasestorage.app',
    measurementId: 'G-RVQTTE36BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCTcY81bFOVB6amnNciKNgnjH4FEbSNB0',
    appId: '1:499992457670:android:38271065ef2c24521482c7',
    messagingSenderId: '499992457670',
    projectId: 'flowery-cf7c0',
    storageBucket: 'flowery-cf7c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfj1PBtkZU-C90mCrdktSotgp9NoH6STA',
    appId: '1:499992457670:ios:1dd0d6fbc83d59831482c7',
    messagingSenderId: '499992457670',
    projectId: 'flowery-cf7c0',
    storageBucket: 'flowery-cf7c0.firebasestorage.app',
    iosBundleId: 'com.example.flowerECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfj1PBtkZU-C90mCrdktSotgp9NoH6STA',
    appId: '1:499992457670:ios:1dd0d6fbc83d59831482c7',
    messagingSenderId: '499992457670',
    projectId: 'flowery-cf7c0',
    storageBucket: 'flowery-cf7c0.firebasestorage.app',
    iosBundleId: 'com.example.flowerECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxKCX21RQesh5kknlNIv8WLqmmgZj6MEM',
    appId: '1:499992457670:web:86bd6d5b30f79ae51482c7',
    messagingSenderId: '499992457670',
    projectId: 'flowery-cf7c0',
    authDomain: 'flowery-cf7c0.firebaseapp.com',
    storageBucket: 'flowery-cf7c0.firebasestorage.app',
    measurementId: 'G-2XG376RXD2',
  );
}
