// Mocks generated by Mockito 5.4.6 from annotations
// in flower_e_commerce_app/test/Feature/auth/data/repositories/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_e_commerce_app/core/Errors/api_results.dart' as _i4;
import 'package:flower_e_commerce_app/Feature/auth/data/dataSources/auth_local_data_source.dart'
    as _i16;
import 'package:flower_e_commerce_app/Feature/auth/data/dataSources/auth_remote_data_source.dart'
    as _i2;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/request/forget_password_request_entity.dart'
    as _i9;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/request/reset_password_request_entity.dart'
    as _i13;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/request/sign_up_request_entity.dart'
    as _i6;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/request/verify_reset_code_request_entity.dart'
    as _i11;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/response/forget_password_response_entity.dart'
    as _i8;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/response/reset_password_response_entity.dart'
    as _i12;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/response/sign_up_response_entity.dart'
    as _i5;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/response/verify_reset_code_response_entity.dart'
    as _i10;
import 'package:flower_e_commerce_app/Feature/auth/domain/entity/request/sign_in_request_entity.dart'
    as _i15;
import 'package:flower_e_commerce_app/Feature/auth/domain/entity/response/sign_in_response_entity.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i2.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.SignUpResponseEntity>> signup(
          _i6.SignUpRequestEntity? signUpRequestEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [signUpRequestEntity],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.SignUpResponseEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.SignUpResponseEntity>>(
          this,
          Invocation.method(
            #signup,
            [signUpRequestEntity],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.SignUpResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.ForgetPasswordResponseEntity>> forgetPassword(
          _i9.ForgetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i8.ForgetPasswordResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i8.ForgetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.ForgetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i10.VerifyResetCodeResponseEntity>> verifyResetCode(
          _i11.VerifyResetCodeRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [request],
        ),
        returnValue: _i3
            .Future<_i4.ApiResult<_i10.VerifyResetCodeResponseEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i10.VerifyResetCodeResponseEntity>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i10.VerifyResetCodeResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponseEntity>> resetPassword(
          _i13.ResetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i12.ResetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i14.SigninResponseEntity>> signin(
          {required _i15.SigninRequestEntity? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signin,
          [],
          {#request: request},
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i14.SigninResponseEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i14.SigninResponseEntity>>(
          this,
          Invocation.method(
            #signin,
            [],
            {#request: request},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i14.SigninResponseEntity>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i16.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<void>> isGuest() => (super.noSuchMethod(
        Invocation.method(
          #isGuest,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<void>>.value(
            _i7.dummyValue<_i4.ApiResult<void>>(
          this,
          Invocation.method(
            #isGuest,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<_i4.ApiResult<void>> writeToken({required String? token}) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeToken,
          [],
          {#token: token},
        ),
        returnValue: _i3.Future<_i4.ApiResult<void>>.value(
            _i7.dummyValue<_i4.ApiResult<void>>(
          this,
          Invocation.method(
            #writeToken,
            [],
            {#token: token},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<_i4.ApiResult<void>> setRememberMe({required bool? rememberMe}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRememberMe,
          [],
          {#rememberMe: rememberMe},
        ),
        returnValue: _i3.Future<_i4.ApiResult<void>>.value(
            _i7.dummyValue<_i4.ApiResult<void>>(
          this,
          Invocation.method(
            #setRememberMe,
            [],
            {#rememberMe: rememberMe},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<bool> getRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #getRememberMe,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
