// Mocks generated by Mockito 5.4.5 from annotations
// in flower_e_commerce_app/test/Feature/auth/presentation/viewModel/forgetPassword/forget_password_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_e_commerce_app/core/Errors/api_results.dart' as _i4;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/request/forget_password_request_entity.dart'
    as _i6;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/request/reset_password_request_entity.dart'
    as _i13;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/request/verify_reset_code_request_entity.dart'
    as _i10;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/response/forget_password_response_entity.dart'
    as _i5;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/response/reset_password_response_entity.dart'
    as _i12;
import 'package:flower_e_commerce_app/Feature/auth/domain/entities/response/verify_reset_code_response_entity.dart'
    as _i9;
import 'package:flower_e_commerce_app/Feature/auth/domain/useCases/forget_password_use_case.dart'
    as _i2;
import 'package:flower_e_commerce_app/Feature/auth/domain/useCases/reset_password_use_case.dart'
    as _i11;
import 'package:flower_e_commerce_app/Feature/auth/domain/useCases/verify_reset_code_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ForgetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUseCase extends _i1.Mock
    implements _i2.ForgetPasswordUseCase {
  MockForgetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>> invoke(
          _i6.ForgetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #invoke,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>>);
}

/// A class which mocks [VerifyResetCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeUseCase extends _i1.Mock
    implements _i8.VerifyResetCodeUseCase {
  MockVerifyResetCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i9.VerifyResetCodeResponseEntity>> invoke(
          _i10.VerifyResetCodeRequestEntity? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [resetCode],
        ),
        returnValue: _i3
            .Future<_i4.ApiResult<_i9.VerifyResetCodeResponseEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i9.VerifyResetCodeResponseEntity>>(
          this,
          Invocation.method(
            #invoke,
            [resetCode],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i9.VerifyResetCodeResponseEntity>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i11.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponseEntity>> invoke(
          _i13.ResetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i12.ResetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #invoke,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponseEntity>>);
}
